version: "3.9"

services:
  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      REDIS_URL: redis://redis:6379
    volumes:
      - ./pastebin:/app/pastebin

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: >
      watchmedo auto-restart
      --directory=/app/pastebin
      --pattern=*.py
      --recursive
      --
      celery -A pastebin worker -l info
    depends_on:
      - redis
      - backend
    volumes:
      - ./pastebin:/app/pastebin

  celery_beat:
    build: .
    command: celery -A pastebin beat -l info
    depends_on:
      - redis
      - backend
    volumes:
      - ./pastebin:/app/pastebin

volumes:
  db_data:
  redis_data:
