# Generated by Django 5.2 on 2025-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='expiration_type',
            field=models.CharField(default='N', max_length=15),
        ),
    ]
