# Generated by Django 5.2 on 2025-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
