# Generated by Django 5.2 on 2025-12-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_paste_views_alter_paste_expiration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
