# Generated by Django 5.2 on 2025-12-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_paste_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='views',
        ),
    ]
