# Generated by Django 5.2 on 2025-12-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_alter_paste_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
