# Generated by Django 5.2 on 2025-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_remove_paste_is_private_remove_paste_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='is_private',
            field=models.CharField(default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='paste',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
